### ISSUE TITLE
Cannot join to Coursera platform

### ISSUE THREAD

**Issue by Djohrdee** [transifex/transifex#334]
Hi,

I'm Jordi (transifex nickname: Xeto.o) and I've been assigned a translation to "Introduction to logic".

1- In the "Explore" tag doesn't appear the "Coursera Organization" to be able to join in.
2- The link of the course doesn't work (https://www.transifex.com/organization/coursera/dashboard/coursera-intrologic)

What could I do?

Thanks in advance, 

Jordi.

**Comment by glezos** [comment]
Jordi, please navigate this page to find out how to join: https://www.coursera.org/about/translate

In the future please email our support team at support@transifex.com for questions.. The issues will be much better managed there. Thanks!
