### ISSUE TITLE
Clicking on 'sign up' under I am a translator. How do I sign up? fails to open sign up page.

### ISSUE THREAD

**Issue by csasalu** [transifex/transifex#335]
Goto https://www.transifex.com/pricing/   > I am a translator. How do I sign up? > Click on 'Sign up'

Fails to open sign up page.

**Comment by powerfool** [comment]
This is fixed now, thank you. 
Can you confirm it works for you too?

**Comment by csasalu** [comment]
Works now. Thank you.

On Wed, Apr 29, 2015 at 10:16 AM, Dimitris Tzortzis <
notifications@github.com> wrote:

> This is fixed now, thank you.
> Can you confirm it works for you too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transifex/transifex/issues/335#issuecomment-97347014>.
>



-- 
Chetak
