### ISSUE TITLE
error when signing up with github account

### ISSUE THREAD

**Issue by tallistroan** [transifex/transifex#347]
When trying to sign-up at https://www.transifex.com/signup/ with my github account I get the error message

*Looks like you followed a bad link. If you think it's our fault, please let us know.
Here's a link to the homepage. You know, just in case.*

I tried it with FF Nightly 42.0a1 and Google Chrome Version 44.0.2403.125 m

**Comment by lolletsoc** [comment]
@tallistroan, all fixed - sorry about that!
