### ISSUE TITLE
Clicking the web browser's "Back" button in a Transfifex webpage

### ISSUE THREAD

**Issue by KNTRO** [transifex/transifex#350]
Hi there,

Please, I need someone to try this.

First, [go here] (https://www.transifex.com/moonchild-productions/teams/) and select any team from the left column. Then, use the "Back" button in your web browser.

In my case -Lubuntu 15.04, updated, Firefox 39- I've got this:
*[{"cla_text": "", "auto_join": false, "join_requests_count": 0, "cla_flag": false, "collaborators_count": 7, "name": "Pale Moon team", "managers_count": 0, "projects_count": 1, "id": 40569}]*

Is anyone else able to reproduce this?

Thank you.

**Comment by dimoschi** [comment]
Hey @KNTRO,

I wasn't able to reproduce the reported issue.
Can you please provide more info?

Dimos

**Comment by KNTRO** [comment]
@dimoschi Mmm… Couldn't reproduce it with Pale Moon now. :sweat_smile:

Please, wait until tomorrow that I'm gonna retry this after updating both Lubuntu & Firefox. Then I'll comment if I still experience the same issue or not.

**Comment by dimoschi** [comment]
@KNTRO Please send us any bug reports at the support mail: support@transifex.com

**Comment by KNTRO** [comment]
@dimoschi Just tried this again using Lubuntu 15.04, updated, with Mozilla Firefox 40.0.3 and no glitch has happened. So I guess, it was a problem with Lubuntu and/or Firefox, but it seems to be solved now, so I'm closing this issue! :ok_hand:

**Comment by KNTRO** [comment]
Sorry, wrong button clicked. :sweat_smile:
