### ISSUE TITLE
Notification links for joining users send to a 404

### ISSUE THREAD

**Issue by Fmstrat** [transifex/transifex#353]
Hi, when getting notifications that users want to join the team, a 404 is in place for the link in the notification.

`Notifications for changes of teams : The user Maxmiller Dutra has asked to join the team for the language Portuguese (Brazil) of the project ownNote.
1 hour, 1 minute ago`

The phrase `asked to join` points to `https://www.transifex.com/ownnote/teams/41462/pt_BR/` which results in a 404.

Thanks!

**Comment by dimoschi** [comment]
Hey, can you please tell me under which Organization is that project?

**Comment by dimoschi** [comment]
@Fmstrat Thank you for submitting your request.

I have notified the user to follow the right link (https://www.transifex.com/nowsci/teams/41462/pt_BR/). We will monitor the notifications more closely, as they could have been affected by our recent URL schema changes.

Regards,
Dimos
