### ISSUE TITLE
No Leaderboard information is displayed

### ISSUE THREAD

**Issue by yanhuisong** [transifex/transifex#354]
There are not any information on my Leaderboard.   https://translate-coursera.org/gtc/leaderboard.
My Leaderboard looks like this:

Rank                 Name           Status            Language         Transifex user            Score

{{x.rank}} {{x.name}} {{x.status}} {{x.language}} {{x.transifex}} {{x.score | number:0}} 

Please wait while loading...

Go back to the GTC Headquarters

So, I am UNABLE to find my name at my Leaderboard. My transifex username is yanhuisong.
Please help me solve this problem.

**Comment by dimoschi** [comment]
Hey @yanhuisong,

I am not sure how can I help you. This leaderboard is being maintained by Coursera. if you can't find your name, you must contact Coursera support at translate@coursera.org
