### ISSUE TITLE
Introduction to Public Speaking Not Found

### ISSUE THREAD

**Issue by Gordynchuk** [transifex/transifex#358]
Hi!
I have been working on my translation into Ukrainian and I had a server error, I refreshed the page and suddenly it was not found. Please help because I still have work to do. Thank you!

**Comment by glezos** [comment]
Can you please give us the URL?

**Comment by Gordynchuk** [comment]
https://www.transifex.com/coursera/coursera-od-orpxgqt0ees5diiacoo5jq/translate/#uk

**Comment by Gordynchuk** [comment]
Should I remain hopeful?

**Comment by Gordynchuk** [comment]
I am sorry to be a nuisance, but I have a deadline tomorrow. I still have 2,5 video translations to add. Do you think it might be fixed today? Thank you!

**Comment by diegobz** [comment]
@Gordynchuk please verify with Coursera if you still have access to that project.

I'm closing it for now as we couldn't find any evidence of issues. Feel free to contact our support if you still have issue.

**Comment by Gordynchuk** [comment]
Hi!
I still can not see this page. How could I have lost access to that project? Do you mean that someone excluded me from the team? I tried to log in with a different name and password and I still could not see this page. And it was not even a completed project.
