### ISSUE TITLE
Introduction to Public Speaking Not Found+lost translation

### ISSUE THREAD

**Issue by Gordynchuk** [transifex/transifex#359]
Hi!
So, I have lost access to my page.
I tried to log in with a name Sholechka.
And I saw that this course that was full yesterday (personally I was responsible for 19 videos and I did 16.5) is empty today. 
I wonder if all the translations are lost.

**Comment by dimoschi** [comment]
Hello!
The administrator of the organization decided to archive the Project.
Your translations have not been lost, they remain in the Translation Memory and they are being used in other Projects.
For more information, please contact the Organization Administrators you can find here: https://www.transifex.com/coursera/public/

**Comment by Gordynchuk** [comment]
Hi!
Thank you! What if I still have 2 translations to add? What should I do? Ask the Organization Administrators?
