### ISSUE TITLE
Use the primary email for GitHub signup

### ISSUE THREAD

**Issue by nyuszika7h** [transifex/transifex#361]
When I signed up using GitHub, I was wondering why my Gravatar wasn't working, then I realized Transifex used the wrong email address – the first one in the list, which happened to be my school email, rather than the one marked as primary. I managed to change it before contributing to anything, but it would be nice if you could fix this.

**Comment by glezos** [comment]
You can change your primary email address by clicking on the icon at the top-right corner → Profile → User Settings → Change email.

https://www.transifex.com/user/settings/email/

Feel free to reach out to us with further questions at http://www.transifex.com/contact.
