### ISSUE TITLE
Renaming: old project uri does not forward to new project uri

### ISSUE THREAD

**Issue by 2-4601** [transifex/transifex#363]
This project:
https://www.transifex.com/moxie/textsecure-official/
was recently renamed to:
https://www.transifex.com/moxie/signal-android/

The problem is that the old url does not forward to the new url. This will immediately invalidate all old references without any grace period.

I reported here because the [old page](https://www.transifex.com/moxie/textsecure-official/) told me so:
_"Looks like you followed a bad link. If you think it's our fault, please [let us know](http://code.transifex.com/transifex/issues/)."_

Possibly related #182

**Comment by pejakm** [comment]
@2-4601 https://github.com/transifex/transifex/commit/bae89a6e2e2f05bda08d5900b8e112ef5306268f
