### ISSUE TITLE
Key Value JSON not import

### ISSUE THREAD

**Issue by sl45sms** [transifex/transifex#366]
I get the message "The file you uploaded does not seem to be valid for the chosen file format."
when I've try to import the following

https://raw.githubusercontent.com/sl45sms/FlapAtSpace/master/js/i18n/el.json

I'm also trying to remove any special character ie . ! without success

Regards

**Comment by dimoschi** [comment]
Hey @sl45sms, can you please send your request to Transifex Support using our [contact form](https://www.transifex.com/contact/)?
