### ISSUE TITLE
Malayayalam Translation

### ISSUE THREAD

**Issue by salmanfarisvp** [transifex/transifex#367]
Somay malayalam translations are Spam. not correct word or duplicate the same langauge. plzmavoid or delete to those tokens that will helpfull for Translators.

**Comment by dimoschi** [comment]
Hello @salmanfarisvp, if you are already participating in Transifex team, you can either correct them by yourself or you can leave a comment-issue about those translations.

Last, but not least use our contact form found [here](www.transifex.com/contact/) to contact Transifex Support, as we don't provide official support to this repo any more.

**Comment by salmanfarisvp** [comment]
Thanks for the replay....
