### ISSUE TITLE
Problem with umlaut in pot file

### ISSUE THREAD

**Issue by baedert** [transifex/transifex#374]
Hey,

my last name contains an ä and I currently get an error message whenever transifex tries to automatically update my pot file:
> 'ascii' codec can't encode character u'\xe4' in position 53: ordinal not in range(128)

I couldn't find a way to choose another codec for the resource online. Is there a way to fix that or does it require server-side changes?

**Comment by nelefth** [comment]
Hi @baedert.  I would like to inform you that we are already aware of this issue and we have already added this to our backlog for further investigation. 
Please also note that you can contact us at support@transifex.com as we don't provide official support in this repo anymore.
