### ISSUE TITLE
Support for translations in Mayan languages

### ISSUE THREAD

**Issue by julienmalard** [transifex/transifex#376]
I would need to translate my project into several Mayan languages (for the moment, Kaqchikel [ISO: cak, Glottolog: kaqc1270], Tz'utujil [ISO: tzj, Glottolog: tzut1248] and K'iche' [ISO: quc, Glottolog: kich1262]). Would it be possible to add these? If so please do advise what information I should contribute.

**Comment by nelefth** [comment]
@julienmalard would it be possible to send us your request using our contact form [here](https://www.transifex.com/contact/)? That way we can get back to you via email and properly inform you about the status of your request. 
Please note that we don't provide official support in this repo anymore.

**Comment by julienmalard** [comment]
Thank you! I have done that.
