### ISSUE TITLE
tx ERROR: TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by regularlabs** [transifex/transifex#377]
Just installed pip and the transifex client on my OSX Sierra High.
```
sudo easy_install pip
sudo pip install transifex-client
```
No when doing anything with the `tx` command (even the `init`) gives me the error:
```
tx ERROR: TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by nelefth** [comment]
@regularlabs our support team will get back to you via email in order to help you figure this out. The existing ticket will be marked as closed since we don't provide official support in this repo anymore.

We will get back to you on this as soon as possible.
