### ISSUE TITLE
Auto-update failed for the resources (open-edx)

### ISSUE THREAD

**Issue by Ayub-Khan** [transifex/transifex#378]
HI team,

Yesterday Auto updates were failed for a lot of resources. 
![screenshot from 2018-01-01 16-03-20](https://user-images.githubusercontent.com/7721119/34467245-5b228832-ef0d-11e7-9e49-eacb4899c0da.png)

The error message mentioned on the email was 
'There is a syntax error in your file. Line'
This message is not clear, do not have proper knowledge what is the syntax error and where it lies. 
![screenshot from 2018-01-01 16-16-05](https://user-images.githubusercontent.com/7721119/34467293-271746ca-ef0f-11e7-83f1-f64a90f53cba.png)

I have checked one file with the help of msgfmt for which auto-update failed.
here is the out put. 

`msgfmt: django.po: warning: PO file header fuzzy
                   warning: older versions of msgfmt will give an error on this
django.po:8: warning: header field 'Project-Id-Version' still has the initial default value
django.po:8: warning: header field 'PO-Revision-Date' still has the initial default value
django.po:8: warning: header field 'Last-Translator' still has the initial default value
django.po:8: warning: header field 'Language-Team' still has the initial default value
django.po:8: warning: header field 'Language' still has the initial default value
`

could this be the reason that msgfmt used to check for the syntax is old version. 

i tried to manually update the source with same file and it was updated. 

We also receive emails that system is not able to find the translation file. which on checking is available.

What could be the issues causing this ? Is there some thing we could do to avoid such issues in future?

Thanks,

**Comment by nelefth** [comment]
Hi @Ayub-Khan,

Thank you for taking the time to let us know about this. We will further look into this and try to identify the root cause of this failure. 
In the meantime, would it be possible to use our contact form [here](https://www.transifex.com/contact/) and submit this issue? That way we can get back to you via email and properly update you on the progress of our investigation.
Please note that we don't provide official support in this repo anymore.

**Comment by Ayub-Khan** [comment]
@nelefth Sure thanks. It seems this is fixed now. I have created a new ticket for 'File not found' issue which is related to auto update resources. I have used the contact forum to create the issue.
