### ISSUE TITLE
Filipino Translation Request

### ISSUE THREAD

**Issue by sageyuan** [transifex/transifex#379]
Hello Good day sir!
i would like to request a string to be translated from English to Filipino.

**Comment by nelefth** [comment]
Hi @sageyuan 

Regarding your case, would it be possible to use our contact form [here](https://www.transifex.com/contact/) and provide us with more information about your request so as to understand this better and properly assist you? That way we can get back to you via email and provide any clarifications needed.
Please note that we don't provide official support in this repo anymore.
